[package]
name = "ggez-specs-hello-world"
version = "0.1.0"
authors = ["Rafael Delboni <rafadelboni@gmail.com>"]

[dependencies]
ggez = { version = "0.4", features = ["cargo-resource-root"] }
specs = "0.12"
